In [48]:
#Pandas has all functions related to database tables
import pandas as pd

In [13]:
#Assigning the dataset to a vriable
dataset=pd.read_csv("Salary_Data.csv")

In [14]:
#printing the dataset
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [49]:
#splitting input and assigning to a variable -independent
independent=dataset[["YearsExperience"]]

In [50]:
#printing the splitted input dataset
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [51]:
#splitting output  and assigning to a variable -independent
dependent=dataset[["Salary"]]

In [21]:
#printing the splitted output dataset
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [24]:
#splitting training set and test set

In [27]:
from sklearn.model_selection import train_test_split

In [64]:
#x refers input, y refers output
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
regressor=LinearRegression()

In [63]:
#below line will create model
regressor.fit(x_train,y_train)

LinearRegression()

In [37]:
LinearRegression()

LinearRegression()

In [39]:
weight=regressor.coef_

In [40]:
weight

array([[9360.26128619]])

In [41]:
bias=regressor.intercept_

In [42]:
bias

array([26777.3913412])

In [65]:
#storing predicted output in y_pred 
y_pred=regressor.predict(x_test)

In [44]:
y_pred

array([[ 40817.78327049],
       [123188.08258899],
       [ 65154.46261459],
       [ 63282.41035735],
       [115699.87356004],
       [108211.66453108],
       [116635.89968866],
       [ 64218.43648597],
       [ 76386.77615802]])

In [67]:
#evaluating the predicted output
from sklearn.metrics import r2_score

In [66]:
#r_score has value of actual output - predicted output. If r_score has value nearly 1, it indicates the created model 
# has better performance else the model has poor performance
r_score=r2_score(y_test,y_pred)

In [47]:
r_score

0.9740993407213511

In [55]:
#To save the best model
import pickle
filename="Finalized_linear_model.sav"
pickle.dump(regressor,open(filename,'wb'))

In [59]:
#To load the saved model
load_model=pickle.load(open("Finalized_linear_model.sav",'rb'))

In [68]:
#the predicted output value given for input will be stored in result variable
result=load_model.predict([[0]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [62]:
result

array([[26777.3913412]])